### ISSUE TITLE
double tmp paths in embroider builds

### ISSUE THREAD

**Issue by glnster** [ef4/scenario-tester#4]
Context: we are using scenario-tester to test [babel-plugin-ember-test-metadata](https://github.com/babel-plugin-ember-test-metadata/babel-plugin-ember-test-metadata) against Classic & Embroider Ember build scenarios. 

The problem we're seeing is that for Embroider build app scenarios, the file path prefix we get has a double `tmp` path.

Expected path: `/private/var/folders/24/v9y37q75019cv62vg5ms10tw001llm/T/embroider/620a67/tests/acceptance/foo-test.js`

Path we're getting in the Embroider scenario instead: `/private/var/folders/24/v9y37q75019cv62vg5ms10tw001llm/T/embroider/620a67/private/var/folders/24/v9y37q75019cv62vg5ms10tw001llm/T/tmp-72329-6SsJEomJQDVe/tests/acceptance/foo-test.js`

**Comment by ef4** [comment]
Does this actually fail? Because it could be correct, if funny-looking, behavior. 

Under `$TMPDIR/embroider/$PROJECT_HASH`, Embroider recreates as much of your filesystem structure as necessary to maintain the relationships between all the packages that are involved in a build. If some of those packages are themselves in temp (because they were created by scenario-tester), and some are not (because scenario-tester is using symlinks back to real dependencies), you will see the path to temp reproduced within temp, and that is intended.
